### Create a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John Dore Billing",
  "email": "billings@gmail.com",
  "address": "123 Geekie Road, Merrivale, 3291",
  "dateOfBirth": "1990-04-22",
  "registeredDate": "2026-05-18"
}
###