### Update an existing patient entity
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "Njabulo Msomi Updated",
  "email": "njabulo_updated@gmail.com",
  "address": "123 Geekie Road, Merrivale, 3291",
  "dateOfBirth": "1990-04-22"
}